services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.4
    ports:
      - "18080:8080"
    environment:
      KC_DB: dev-file
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ../build/keycloak-personal-access-tokens.jar:/opt/keycloak/providers/keycloak-personal-access-tokens.jar:ro
      - ../build/keycloak-personal-access-tokens-theme.jar:/opt/keycloak/providers/keycloak-personal-access-tokens-theme.jar:ro
      - ./realm/test-realm.json:/opt/keycloak/data/import/test-realm.json:ro
    command: start-dev --import-realm
